

  
    
  


  





  

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.53 with theme Tranquilpeak 0.4.3-BETA">
    <title>Como um cientista de dados pesquisa o carro que quer comprar?</title>
    <meta name="author" content="Ítalo Cegatta">
    <meta name="keywords" content="">

    <link rel="icon" href="/favicon.png">
    

    
    <meta name="description" content="Estou naquela parte da vida em que se planeja comprar um carro. Como eu sou, acima de todos os sonhos, pão duro, decidir qual marca, modelo, versão e ano do veículo não vai ser fácil. Pensando nisso resolvi escrever um pacote no R para me ajudar a tomar esta decisão. O objetivo deste post é apresentar o pacote e as funções que auxiliam na coleta das informações da tabela FIPE.">
    <meta property="og:description" content="Estou naquela parte da vida em que se planeja comprar um carro. Como eu sou, acima de todos os sonhos, pão duro, decidir qual marca, modelo, versão e ano do veículo não vai ser fácil. Pensando nisso resolvi escrever um pacote no R para me ajudar a tomar esta decisão. O objetivo deste post é apresentar o pacote e as funções que auxiliam na coleta das informações da tabela FIPE.">
    <meta property="og:type" content="blog">
    <meta property="og:title" content="Como um cientista de dados pesquisa o carro que quer comprar?">
    <meta property="og:url" content="/como-um-cientista-de-dados-pesquisa-o-carro-que-quer-comprar/">
    <meta property="og:site_name" content="Italo Cegatta">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Italo Cegatta">
    <meta name="twitter:description" content="Estou naquela parte da vida em que se planeja comprar um carro. Como eu sou, acima de todos os sonhos, pão duro, decidir qual marca, modelo, versão e ano do veículo não vai ser fácil. Pensando nisso resolvi escrever um pacote no R para me ajudar a tomar esta decisão. O objetivo deste post é apresentar o pacote e as funções que auxiliam na coleta das informações da tabela FIPE.">
    
    

    
    

    
      <meta property="og:image" content="http://i.imgur.com/9MOS3vs.png">
    

    
      <meta property="og:image" content="http://i.imgur.com/1gZcM9L.png">
    
    
      <meta property="og:image" content="http://i.imgur.com/d1eBDPc.png">
    
    

    

    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">      
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="/css/style-jsjn0006wyhpyzivf6yceb31gvpjatbcs3qzjvlumobfnugccvobqwxnnaj8.min.css" />
    
    

    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-77144482-1', 'auto');
	
	ga('send', 'pageview');
}
</script>

    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="2">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="/">Italo Cegatta</a>
  </div>
  
    
      <a class="header-right-picture "
         href="/#about">
    
    
    
      
        <img class="header-picture" src="http://i.imgur.com/9MOS3vs.png" alt="Foto do autor" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="2">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="/#about">
          <img class="sidebar-profile-picture" src="http://i.imgur.com/9MOS3vs.png" alt="Foto do autor" />
        </a>
        <h4 class="sidebar-profile-name">Ítalo Cegatta</h4>
        
          <h5 class="sidebar-profile-bio">R, Floresta e Data Science</h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Início</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categorias</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      
      <span class="sidebar-button-desc">Arquivo</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/sobre">
    
      <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      
      <span class="sidebar-button-desc">Sobre</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/mailto:italocegatta@gmail.com">
    
      <i class="sidebar-button-icon fa fa-lg fa-envelope"></i>
      
      <span class="sidebar-button-desc">Email</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/italocegatta">
    
      <i class="sidebar-button-icon fa fa-lg fa-code"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://www.linkedin.com/in/italocegatta">
    
      <i class="sidebar-button-icon fa fa-lg fa-briefcase"></i>
      
      <span class="sidebar-button-desc">Linkedin</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="http://eepurl.com/b03nmD">
    
      <i class="sidebar-button-icon fa fa-lg fa-address-book"></i>
      
      <span class="sidebar-button-desc">Inscreva-se</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/index.xml">
    
      <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      
      <span class="sidebar-button-desc">RSS</span>
    </a>
  </li>


    </ul>
  </div>
</nav>

      
  <div class="post-header-cover
              text-center
              "
       style="background-image:url('http://i.imgur.com/d1eBDPc.png')"
       data-behavior="2">
    
  </div>


      <div id="main" data-behavior="2"
        class="hasCover
               hasCoverMetaOut
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-center">
  
    <h1 class="post-title" itemprop="headline">
      Como um cientista de dados pesquisa o carro que quer comprar?
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2017-07-29T00:00:00Z">
        
  
  
  
  
    29 Julho 2017
  

      </time>
    
    
  
  
    <span>em</span>
    
      <a class="category-link" href="/categories/data-science">Data Science</a>
    
  

  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              
              


<p>Estou naquela parte da vida em que se planeja comprar um carro. Como eu sou, acima de todos os sonhos, pão duro, decidir qual marca, modelo, versão e ano do veículo não vai ser fácil. Pensando nisso resolvi escrever um pacote no R para me ajudar a tomar esta decisão. O objetivo deste post é apresentar o pacote e as funções que auxiliam na coleta das informações da tabela <a href="http://veiculos.fipe.org.br/">FIPE</a>.</p>
<p>Para aqueles que já passaram pela etapa de compra ou venda de um carro, provavelmente já consultaram a famosa tabela. Nas palavras do próprio site da FIPE:</p>
<blockquote>
<p>A Tabela Fipe expressa preços médios de veículos no mercado nacional, servindo apenas como um parâmetro para negociações ou avaliações. Os preços efetivamente praticados variam em função da região, conservação, cor, acessórios ou qualquer outro fator que possa influenciar as condições de oferta e procura por um veículo específico.</p>
</blockquote>
<p>A motivação para este pacote foi exclusivamente pessoal e por isso a utilização das funções está bastante restrita. Por isso, se alguém quiser ajudar no desenvolvimento do pacote é só chegar e mandar um <a href="https://github.com/italocegatta/fipe">Pull Request</a> no Github, contribuições serão muito bem-vindas.</p>
<p>Primeiro vou mostrar as funções e o workflow idealizado para o pacote. Queremos saber, por enquanto, o preço atual de uma BMW X6 M ano 2015. O primeiro passo é definir o mês de referência que se deseja consultar o preço do veículo. A FIPE disponibiliza os valores consolidados desde janeiro de 2001.</p>
<pre class="r"><code>if (!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;)
pacman::p_load(dplyr, purrr, stringr, tidyr, forcats, ggplot2)
pacman::p_load_gh(&quot;italocegatta/fipe&quot;)</code></pre>
<pre class="r"><code>fipe_referencia()</code></pre>
<pre><code>## # A tibble: 216 x 2
##    data_ref   cod_ref
##    &lt;date&gt;       &lt;int&gt;
##  1 2018-12-01     236
##  2 2018-11-01     235
##  3 2018-10-01     234
##  4 2018-09-01     233
##  5 2018-08-01     232
##  6 2018-07-01     231
##  7 2018-06-01     230
##  8 2018-05-01     229
##  9 2018-04-01     228
## 10 2018-03-01     227
## # ... with 206 more rows</code></pre>
<p>Como o objetivo saber o preço atual do veículo, pegaremos o código <code>215</code> (mês em que escrevo este post). Agora vamos procurar o código da marca BMW. Note que precisamos inserir o código do mês de referência para consultar a marca, essa é uma exigência do site da FIPE. Lembrando que o pacote não possui nenhum banco de dados armazenado, todas as informações são consultadas no site da tabela FIPE no ato da execução da função.</p>
<pre class="r"><code>fipe_marca(cod_ref = 215)</code></pre>
<pre><code>## # A tibble: 87 x 2
##    marca        cod_marca
##    &lt;chr&gt;            &lt;int&gt;
##  1 Acura                1
##  2 Agrale               2
##  3 Alfa Romeo           3
##  4 AM Gen               4
##  5 Asia Motors          5
##  6 ASTON MARTIN       189
##  7 Audi                 6
##  8 BMW                  7
##  9 BRM                  8
## 10 Buggy                9
## # ... with 77 more rows</code></pre>
<p>Por sorte, o código <code>7</code> da BMW aparece logo nos primeiros valores por ordem alfabética. Podemos seguir para o próximo passo e pegar o código do modelo que queremos. A consulta a baixo mostras que a BMW tem 221 modelos cadastrados na tabela FIPE. Como já definimos o modelo que queremos, vamos filtrar do dataframe para enxergar o código do modelo.</p>
<pre class="r"><code>(bmw &lt;- fipe_modelo(cod_ref = 215, cod_marca = 7))</code></pre>
<pre><code>## # A tibble: 221 x 2
##    modelo                                 cod_modelo
##    &lt;chr&gt;                                       &lt;int&gt;
##  1 116iA 1.6 TB 16V 136cv 5p                    6146
##  2 118iA 2.0 16V 136cv 3p                       5576
##  3 118iA 2.0 16V 136cv 5p                       4960
##  4 118iA Full 1.6 TB 16V 170cv 5p               6147
##  5 118iA/ Urban/Sport 1.6 TB 16V 170cv 5p       5923
##  6 120i 2.0 16V 150cv/ 156cv 5p                  152
##  7 120iA 2.0 16V 150cv/ 156cv 5p                 153
##  8 120iA 2.0 16V 156cv 3p                       4700
##  9 120iA Cabrio 2.0 16V 156cv 2p                4683
## 10 120iA Sport 2.0/ActiveFlex 16V Aut.          7178
## # ... with 211 more rows</code></pre>
<pre class="r"><code>filter(bmw, str_detect(modelo, &quot;X6 M&quot;))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   modelo                            cod_modelo
##   &lt;chr&gt;                                  &lt;int&gt;
## 1 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut.       5189</code></pre>
<p>Pronto, agora já sabemos que o código que a FIPE dá para o modelo X6 M é o <code>5189</code>. Teríamos tudo pronto, se não fosse o padrão que a FIPE adota no campo<code>ano</code>, onde o ano do modelo é acrescido de um código de combustível. A diferenciação para os “0 km” é feita na mesma coluna, utilizando a identificação 32000-*. Enfim, contornando as falhas estruturais no banco de dados deles, agora sabemos os códigos que identificam o ano do modelo, bem como o carro 0 km. Como eu optei por procurar o valor do carro 2015, iremos considerar o código <code>2015-1</code>.</p>
<pre class="r"><code>fipe_ano(cod_ref = 215, cod_marca = 7, cod_modelo = 5189)</code></pre>
<pre><code>## # A tibble: 9 x 2
##   ano   cod_ano
##   &lt;chr&gt; &lt;chr&gt;  
## 1 0 km  32000-1
## 2 2017  2017-1 
## 3 2016  2016-1 
## 4 2015  2015-1 
## 5 2014  2014-1 
## 6 2013  2013-1 
## 7 2012  2012-1 
## 8 2011  2011-1 
## 9 2010  2010-1</code></pre>
<p>Agora sim vamos ao bendito preço da BMW!</p>
<pre class="r"><code>fipe(cod_ref = 215, cod_marca = 7, cod_modelo = 5189, cod_ano = &quot;2015-1&quot;) %&gt;% 
  glimpse()</code></pre>
<pre><code>## Observations: 1
## Variables: 7
## $ cod_fipe    &lt;chr&gt; &quot;009144-8&quot;
## $ ref         &lt;date&gt; 2017-07-01
## $ marca       &lt;chr&gt; &quot;BMW&quot;
## $ modelo      &lt;chr&gt; &quot;X6 M 4.4 4x4 V8 32V Bi-Turbo Aut.&quot;
## $ ano         &lt;chr&gt; &quot;2015&quot;
## $ combustivel &lt;chr&gt; &quot;Gasolina&quot;
## $ valor       &lt;dbl&gt; 368603</code></pre>
<p>Achamos o preço do carro que eu queria. Apenas R$ 368 mil. Uma pechincha. Obviamente, saber quanto vale uma BMW X6 não faz diferença alguma no meu dia. Um abraço pra quem tem condições de comprar um carro desse sem precisar vender um rim.</p>
<p>Agora que já conhecemos as funções e o fluxo para consultar o valor dos carros, vamos ampliar a consulta e justificar as horas que passamos aprendendo a programar. Já sabemos o preço do X6 M em julho/2017, mas e nos meses anteriores? Como será que foi a depreciação média do carro usado nos últimos meses? E os outros modelos X6, quanto será que estão valendo?</p>
<p>Digamos que, agora, estas questões podem ser respondidas de forma bem rápida. Eu mostro.</p>
<p>Vamos retomar os passos, mas agora no nível hard. Vou analisar o comportamento dos preços desde 2009. Para deixar a consulta mais rápida, serão considerados apenas 3 meses de referência por ano.</p>
<pre class="r"><code>(base_marca &lt;- fipe_referencia() %&gt;%
  filter(data_ref %in% seq.Date(as.Date(&quot;2009-01-01&quot;), as.Date(&quot;2017-07-01&quot;), by = &quot;4 months&quot;)) %&gt;%
  mutate(marca = map(cod_ref, fipe_marca)) %&gt;%
  unnest() %&gt;% 
  filter(marca == &quot;BMW&quot;)
)</code></pre>
<pre><code>## # A tibble: 26 x 4
##    data_ref   cod_ref marca cod_marca
##    &lt;date&gt;       &lt;int&gt; &lt;chr&gt;     &lt;int&gt;
##  1 2017-05-01     212 BMW           7
##  2 2017-01-01     202 BMW           7
##  3 2016-09-01     196 BMW           7
##  4 2016-05-01     191 BMW           7
##  5 2016-01-01     187 BMW           7
##  6 2015-09-01     183 BMW           7
##  7 2015-05-01     179 BMW           7
##  8 2015-01-01     174 BMW           7
##  9 2014-09-01     170 BMW           7
## 10 2014-05-01     166 BMW           7
## # ... with 16 more rows</code></pre>
<p>Notem que agora temos um dataframe com códigos de referência entre janeiro/2008 a maio/2017. Seguindo a análise, precisamos encontrar os códigos dos modelos X6.</p>
<pre class="r"><code>(base_modelo &lt;- mutate(base_marca, modelo = map2(cod_ref, cod_marca, fipe_modelo)) %&gt;%
  unnest() %&gt;% 
  filter(str_detect(modelo, &quot;X6&quot;))
)</code></pre>
<pre><code>## # A tibble: 82 x 6
##    data_ref   cod_ref marca cod_marca modelo                     cod_modelo
##    &lt;date&gt;       &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;                           &lt;int&gt;
##  1 2017-05-01     212 BMW           7 X6 M 4.4 4x4 V8 32V Bi-Tu~       5189
##  2 2017-05-01     212 BMW           7 X6 XDRIVE 35i 3.0 306cv B~       4745
##  3 2017-05-01     212 BMW           7 X6 XDRIVE 50i 4.4 407cv B~       4746
##  4 2017-05-01     212 BMW           7 X6 XDRIVE 50i M Sport 4.4~       7088
##  5 2017-01-01     202 BMW           7 X6 M 4.4 4x4 V8 32V Bi-Tu~       5189
##  6 2017-01-01     202 BMW           7 X6 XDRIVE 35i 3.0 306cv B~       4745
##  7 2017-01-01     202 BMW           7 X6 XDRIVE 50i 4.4 407cv B~       4746
##  8 2017-01-01     202 BMW           7 X6 XDRIVE 50i M Sport 4.4~       7088
##  9 2016-09-01     196 BMW           7 X6 M 4.4 4x4 V8 32V Bi-Tu~       5189
## 10 2016-09-01     196 BMW           7 X6 XDRIVE 35i 3.0 306cv B~       4745
## # ... with 72 more rows</code></pre>
<p>O próximo passo é pegar, para cada versão, os diferentes anos de fabricação do carro. A função vai consultar os anos de fabricação que a FIPE consolidou para cada uma das 82 linhas (combinação entre modelo e mês de referência).</p>
<pre class="r"><code>(base_consulta &lt;- mutate(base_modelo, ano = pmap(list(cod_ref, cod_marca, cod_modelo), fipe_ano)) %&gt;%
  unnest()
)</code></pre>
<pre><code>## # A tibble: 480 x 8
##    data_ref   cod_ref marca cod_marca modelo       cod_modelo ano   cod_ano
##    &lt;date&gt;       &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;             &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  
##  1 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 0 km  32000-1
##  2 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2017  2017-1 
##  3 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2016  2016-1 
##  4 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2015  2015-1 
##  5 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2014  2014-1 
##  6 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2013  2013-1 
##  7 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2012  2012-1 
##  8 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2011  2011-1 
##  9 2017-05-01     212 BMW           7 X6 M 4.4 4x~       5189 2010  2010-1 
## 10 2017-05-01     212 BMW           7 X6 XDRIVE 3~       4745 0 km  32000-1
## # ... with 470 more rows</code></pre>
<p>Se na sua internet a função anterior demorou, prepara que a próxima vai demorar um tanto mais. Temos 480 requisições para fazer no site da FIPE em busca dos preços que queremos.</p>
<pre class="r"><code>(consulta &lt;- mutate(
  base_consulta, 
  consulta = pmap(list(cod_ref, cod_marca, cod_modelo, cod_ano), fipe)
  )  %&gt;%
  select(consulta) %&gt;% 
  unnest() %&gt;% 
  select(ref, modelo, ano, valor)
)</code></pre>
<pre><code>## # A tibble: 480 x 4
##    ref        modelo                            ano    valor
##    &lt;date&gt;     &lt;chr&gt;                             &lt;chr&gt;  &lt;dbl&gt;
##  1 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 0 km  644550
##  2 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2017  520193
##  3 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2016  475803
##  4 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2015  365088
##  5 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2014  317505
##  6 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2013  291749
##  7 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2012  231191
##  8 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2011  204481
##  9 2017-05-01 X6 M 4.4 4x4 V8 32V Bi-Turbo Aut. 2010  193629
## 10 2017-05-01 X6 XDRIVE 35i 3.0 306cv Bi-Turbo  0 km  415744
## # ... with 470 more rows</code></pre>
<p>Depois de 4 passos, temos o banco de dados desejado. Imagina coletar estes dados, na mão, pelo site oficial!</p>
<p>Bom agora o pacote está apresentado. Pretendo fazer outros posts com estudos de casos mais específicos, portanto vou deixar apenas um gráfico que resume a consulta que acabamos de fazer.</p>
<pre class="r"><code>consulta %&gt;%
  mutate(ano = fct_relevel(ano, &quot;0 km&quot;, after = Inf)) %&gt;% 
  ggplot(aes(ref, valor, color =  ano, group = ano)) +
    geom_line(color = &quot;grey30&quot;) +
    geom_point(size = 3) +
    facet_wrap(~modelo) +
    labs(
      x = &quot;Mês de refêrencia&quot;,
      y = &quot;Valor (R$)&quot;,
      color = &quot;Ano do \nmodelo&quot;
    ) +
    scale_y_continuous(breaks = seq(0, 700000, 50000), labels = scales::dollar_format(prefix = NULL, big.mark = &quot;.&quot;)) +
    scale_x_date(date_breaks = &quot;1 year&quot;, date_labels = &quot;%b/%y&quot;) +
    scale_color_viridis_d() +
    theme_bw() +
    theme(legend.position = &quot;top&quot;) </code></pre>
<p><img src="/post/2017-07-29-como-um-cientista-de-dados-pesquisa-o-carro-que-quer-comprar_files/figure-html/plot_fipe-1.svg" width="960" /></p>
<p>Caso tenha alguma dúvida ou sugestão sobre o post, fique à vontade para fazer um comentário ou me contatar por E-mail.</p>
<pre class="r"><code>sessioninfo::session_info(c(&quot;readr&quot;, &quot;dplyr&quot;, &quot;ggplot2&quot;, &quot;purrr&quot;, &quot;stringr&quot;, &quot;tidyr&quot;, &quot;forcats&quot;, &quot;fipe&quot;))</code></pre>
<pre><code>## - Session info ----------------------------------------------------------
##  setting  value                       
##  version  R version 3.5.1 (2018-07-02)
##  os       Windows 10 x64              
##  system   x86_64, mingw32             
##  ui       RTerm                       
##  language (EN)                        
##  collate  Portuguese_Brazil.1252      
##  ctype    Portuguese_Brazil.1252      
##  tz       America/Sao_Paulo           
##  date     2018-12-31                  
## 
## - Packages --------------------------------------------------------------
##  package      * version    date       lib
##  assertthat     0.2.0      2017-04-11 [1]
##  BH             1.66.0-1   2018-02-13 [1]
##  bindr          0.1.1      2018-03-13 [1]
##  bindrcpp     * 0.2.2      2018-03-29 [1]
##  cli            1.0.1      2018-09-25 [1]
##  clipr          0.4.1      2018-06-23 [1]
##  colorspace     1.3-2      2016-12-14 [1]
##  crayon         1.3.4      2017-09-16 [1]
##  curl           3.2        2018-03-28 [1]
##  digest         0.6.18     2018-10-10 [1]
##  dplyr        * 0.7.8      2018-11-10 [1]
##  fansi          0.4.0      2018-10-05 [1]
##  fipe         * 0.0.0.9000 2018-12-31 [1]
##  forcats      * 0.3.0      2018-02-19 [1]
##  ggplot2      * 3.1.0      2018-10-25 [1]
##  glue           1.3.0      2018-07-17 [1]
##  gtable         0.2.0      2016-02-26 [1]
##  hms            0.4.2      2018-03-10 [1]
##  httr           1.4.0      2018-12-11 [1]
##  jsonlite       1.6        2018-12-07 [1]
##  labeling       0.3        2014-08-23 [1]
##  lattice        0.20-35    2017-03-25 [2]
##  lazyeval       0.2.1      2017-10-29 [1]
##  lubridate      1.7.4      2018-04-11 [1]
##  magrittr       1.5        2014-11-22 [1]
##  MASS           7.3-50     2018-04-30 [2]
##  Matrix         1.2-14     2018-04-13 [2]
##  mgcv           1.8-24     2018-06-23 [2]
##  mime           0.6        2018-10-05 [1]
##  munsell        0.5.0      2018-06-12 [1]
##  nlme           3.1-137    2018-04-07 [2]
##  openssl        1.1        2018-11-15 [1]
##  pillar         1.3.1      2018-12-15 [1]
##  pkgconfig      2.0.2      2018-08-16 [1]
##  plogr          0.2.0      2018-03-25 [1]
##  plyr           1.8.4      2016-06-08 [1]
##  purrr        * 0.2.5      2018-05-29 [1]
##  R6             2.3.0      2018-10-04 [1]
##  RColorBrewer   1.1-2      2014-12-07 [1]
##  Rcpp           1.0.0      2018-11-07 [1]
##  readr          1.3.1      2018-12-21 [1]
##  reshape2       1.4.3      2017-12-11 [1]
##  rlang          0.3.0.1    2018-10-25 [1]
##  scales         1.0.0      2018-08-09 [1]
##  stringi        1.2.4      2018-07-20 [1]
##  stringr      * 1.3.1      2018-05-10 [1]
##  tibble         1.4.2      2018-01-22 [1]
##  tidyr        * 0.8.2      2018-10-28 [1]
##  tidyselect     0.2.5      2018-10-11 [1]
##  utf8           1.1.4      2018-05-24 [1]
##  viridisLite    0.3.0      2018-02-01 [1]
##  withr          2.1.2      2018-03-15 [1]
##  source                            
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.0)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  Github (italocegatta/fipe@0445ac6)
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.2)                    
##  CRAN (R 3.5.2)                    
##  CRAN (R 3.5.0)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.2)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.0)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.2)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
##  CRAN (R 3.5.1)                    
## 
## [1] C:/Users/Italo/Documents/R/win-library/3.5
## [2] C:/Program Files/R/R-3.5.1/library</code></pre>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">ETIQUETADO em</span><br/>
                    
  <a class="tag tag--primary tag--small" href="/tags/dplyr/">dplyr</a>

  <a class="tag tag--primary tag--small" href="/tags/purrr/">purrr</a>

  <a class="tag tag--primary tag--small" href="/tags/stringr/">stringr</a>

  <a class="tag tag--primary tag--small" href="/tags/tidyr/">tidyr</a>

  <a class="tag tag--primary tag--small" href="/tags/forcats/">forcats</a>

  <a class="tag tag--primary tag--small" href="/tags/ggplot2/">ggplot2</a>

  <a class="tag tag--primary tag--small" href="/tags/fipe/">fipe</a>

                  </div>
                
              
            
            
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/engenheiro-florestal-ou-cientista-de-dados/" data-tooltip="Engenheiro Florestal ou Cientista de Dados?">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">PRÓXIMO</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/graficos-com-dimensao-espacial-e-temporal/" data-tooltip="Gráficos com dimensão espacial e temporal">
              
                  <span class="hide-xs hide-sm text-small icon-mr">ANTERIOR</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2018 Ítalo Cegatta. All Rights Reserved
  </span>
  <a href="https://github.com/akirak/hugo-tranquilpeak-theme">Tranquilpeak theme</a>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="2">
        
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/engenheiro-florestal-ou-cientista-de-dados/" data-tooltip="Engenheiro Florestal ou Cientista de Dados?">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">PRÓXIMO</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/graficos-com-dimensao-espacial-e-temporal/" data-tooltip="Gráficos com dimensão espacial e temporal">
              
                  <span class="hide-xs hide-sm text-small icon-mr">ANTERIOR</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="2">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="http://i.imgur.com/9MOS3vs.png" alt="Foto do autor" />
    
    <h4 id="about-card-name">Ítalo Cegatta</h4>
    
      <div id="about-card-bio">R, Floresta e Data Science</div>
    
    
      <div id="about-card-job">
        <i class="fa fa-briefcase"></i>
        <br/>
        Suzano Papel e Celulose
      </div>
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        Itapetininga-SP
      </div>
    
  </div>
</div>

    <div id="algolia-search-modal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <span class="close-button"><i class="fa fa-close"></i></span>
      <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
        <span class="searchby-algolia-text text-color-light text-small">by</span>
        <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
      </a>
      <i class="search-icon fa fa-search"></i>
      <form id="algolia-search-form">
        <input type="text" id="algolia-search-input" name="search"
          class="form-control input--large search-input" placeholder="Pesquisar" />
      </form>
    </div>
    <div class="modal-body">
      <div class="no-result text-color-light text-center"></div>
      <div class="results">
        
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/risco-de-incendio-pela-formula-de-monte-alegre/">
                <h3 class="media-heading">Risco de incêndio pela Fórmula de Monte Alegre</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jul 7, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">No setor florestal o fogo é uma questão recorrente e preocupante. Utilizar um índice de risco ou perigo de incêndio ajuda, no mínimo, no planejamento e no alerta para quem mora no entorno de maciços florestais como parques, hortos e plantios florestais.
A Fórmula de Monte Alegre (FMA) é um índice bastante simples, foi proposta em 1972 por Soares (1972) e utiliza apenas a umidade relativa do ar às 13h e a precipitação para calcular o risco de incêndio.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/qual-estado-tem-mais-pau-rodado/">
                <h3 class="media-heading">Qual Estado tem mais pau-rodado?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Mar 3, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Em Cuiabá, cidade que nasci e cresci, pau-rodado é um substantivo que define pessoas que nasceram em outro Estado mas moram em Cuiabá e ali construíram suas vidas. Aliás, Cuiabá sempre foi conhecida por ser uma Cidade super acolhedora e talvez por isso todos encaram o dito pau-rodado de uma forma engraçada e sem qualquer sentido pejorativo.
Muito bem, meu interesse com este post é analisar o comportamento dos fluxos migratórios entre Estados e assim encontrar os Estados que tem mais e menos pau-rodado em sua população residente.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/100-anos-do-posto-meteorologico-da-esalq/">
                <h3 class="media-heading">100 anos do posto meteorológico da ESALQ</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Oct 10, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">No dia 31 de dezembro de 2016 o Posto Meteorológico da ESALQ/USP completou 100 anos de funcionamento. Em “comemoração”&quot; a este belo banco de dados, pretendo fazer alguns gráficos para analisar, sem muita pretensão, como o clima variou de lá pra cá.
No site do Posto podemos encontrar os dados nas escalas diária e mensal. Separei apenas os dados mensais para vermos aqui. Fiz algumas poucas adaptações no banco para poder pelo menos iniciar a análise.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/engenheiro-florestal-ou-cientista-de-dados/">
                <h3 class="media-heading">Engenheiro Florestal ou Cientista de Dados?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Sep 9, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">No meio do colegial tive a sorte de ser ‘convencido’ por um amigo da família que Engenharia Florestal seria uma ótima profissão para mim. Vocês sabem que um jovem de 16 anos pouco sabe sobre o mercado de trabalho. Naquela época o único contato profissional que tive foi como menor aprendiz numa concessionária de veículos.
Chegando na ESALQ para o curso de Eng. Florestal, a primeira coisa que eu fiz foi entrar no Grupo Florestal Monte Olimpo (GFMO).</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/como-um-cientista-de-dados-pesquisa-o-carro-que-quer-comprar/">
                <h3 class="media-heading">Como um cientista de dados pesquisa o carro que quer comprar?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jul 7, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Estou naquela parte da vida em que se planeja comprar um carro. Como eu sou, acima de todos os sonhos, pão duro, decidir qual marca, modelo, versão e ano do veículo não vai ser fácil. Pensando nisso resolvi escrever um pacote no R para me ajudar a tomar esta decisão. O objetivo deste post é apresentar o pacote e as funções que auxiliam na coleta das informações da tabela FIPE.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/graficos-com-dimensao-espacial-e-temporal/">
                <h3 class="media-heading">Gráficos com dimensão espacial e temporal</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jul 7, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">O post de hoje é sobre visualização de dados com dimensão espacial e temporal. Basicamente são gráficos que têm uma representação geográfica associada a informações que variam no tempo. Este tipo de análise é comum no meu dia a dia e por isso resolvi deixar 3 alternativas registradas aqui. O contexto que iremos abordar está relacionado ao banco de dados de focos de incêndios registrados pelo INPE no Programa Queimadas Monitoramento por Satélites.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/interpolacao-pelo-inverso-do-quadrado-da-distancia/">
                <h3 class="media-heading">Interpolação pelo inverso do quadrado da distância</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Apr 4, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">É comum quando temos um determinado valor distribuído espacialmente e queremos estimá-lo para um ponto específico. Existem inúmeras formas de se chegar nesta estimativa, mas quero mostrar apenas uma neste post. O objetivo é estimar o quanto choveu em Itapetininga-SP, a partir de dados de chuva de outras 6 cidades próximas. Utilizaremos para isso os dados das estações automáticas do INMET.
Primeiro, vamos importar e visualizar os dados que temos disponível.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/download-automatico-de-imagens-modis/">
                <h3 class="media-heading">Download automático de imagens MODIS</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jan 1, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">O MODIS (MODerate resolution Imaging Spectroradiometer) faz parte de um programa da NASA para monitoramento da superfície terrestre. Os satélites Terra e Aqua fornecem informações muito interessantes para o setor agroflorestal e nos permite entender de maneira bastante eficaz a dinâmica do uso do solo e de crescimento das nossas culturas.
O MODOIS tem diversos produtos, mas neste post vamos tratar especificamente do produto MOD13Q1, que disponibiliza a cada 16 dias um raster de EVI e NDVI com resolução de 250 m.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/indice-de-uniformidade-pv50/">
                <h3 class="media-heading">Índice de uniformidade (PV50)</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Oct 10, 2016
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">O PV50 é hoje o índice mais utilizado quando queremos expressar a uniformidade de um plantio florestal. Hakamada (2012) apresentou um estudo detalhado sobre diversos índices e concluiu que o PV50 é o índice mais indicado para explicar a relação entre uniformidade, qualidade silvicultural e produtividade em plantios homogêneos de Eucalyptus.
O objetivo deste post é mostrar, passo a passo, como calcular este índice no R e fazer uma breve análise de seus resultados.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/anova-e-teste-de-tukey/">
                <h3 class="media-heading">ANOVA e teste de Tukey</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Sep 9, 2016
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Análise de variância (ANOVA) e testes de médias são métodos comuns em artigos científicos. Você com certeza já viu aquelas letrinhas indicando a diferença entre tratamentos em algum estudo publicado. Por mais que este método esteja entrando em desuso - há uma tendência em abandonar esse tipo de abordagem estatística - penso que ainda o veremos por muitos anos no meio científico.
Como contexto, temos um teste de 5 progênies de eucalipto e queremos avaliar se volume por hectare (nossa variável resposta), difere entre os tratamentos.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
      </div>
    </div>
    <div class="modal-footer">
      <p class="results-count text-medium"
         data-message-zero=""
         data-message-one=""
         data-message-other="">
         19 posts found
      </p>
    </div>
  </div>
</div>
    
  
    
    <div id="cover" style="background-image:url('http://i.imgur.com/0YSWdvY.png');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="/js/script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js"></script>



<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = '\/como-um-cientista-de-dados-pesquisa-o-carro-que-quer-comprar\/';
          
            this.page.identifier = '\/como-um-cientista-de-dados-pesquisa-o-carro-que-quer-comprar\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'italocegatta';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  



    
  </body>
</html>

